// Generated by CoffeeScript 1.4.0
(function() {
  var WP_Resume;

  WP_Resume = (function() {

    function WP_Resume() {
      var taxonomy, _i, _len, _ref;
      switch (pagenow) {
        case "wp_resume_position_page_wp_resume_options":
          jQuery("#wp_resume_help, #wp_resume_clearfix, #multiple, .underHood").hide();
          jQuery("#wp_resume_help_toggle").click(this.toggleHelp);
          jQuery("#toggleMultiple").click(this.toggleMultiple);
          jQuery("#toggleHood").click(this.toggleHood);
          jQuery("#user").change(jQuery(".button-primary").click);
          jQuery("#add_contact_field").click(this.addContactField);
          jQuery(".button-primary").click(this.submitOptions);
          this.addContactField();
          this.makeSortable();
          break;
        case "wp_resume_position":
          jQuery("#publish").click(this.validatePosition);
          _ref = ["wp_resume_section", "wp_resume_organization"];
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            taxonomy = _ref[_i];
            this.addTaxonomyBoxEvents(taxonomy);
          }
          break;
        case "edit-wp_resume_organization":
          jQuery("#parent, #tag-slug").parent().hide();
          jQuery("#tag-name").siblings("p").text(wp_resume.orgName);
          jQuery("#tag-description").attr("rows", "1").siblings("label").text("Location").siblings("p").text(wp_resume.orgLoc);
          break;
        case "edit-wp_resume_section":
          jQuery("#parent").parent().hide();
          jQuery("#tag-description, #tag-slug").parent().hide();
      }
    }

    WP_Resume.prototype.toggleHelp = function() {
      jQuery("#wp_resume_help, #wp_resume_clearfix").toggle("fast");
      if (jQuery(this).text() === wp_resume.more) {
        jQuery(this).text(wp_resume.less);
      } else {
        jQuery(this).text(wp_resume.more);
      }
      return false;
    };

    WP_Resume.prototype.validatePosition = function(e) {
      if (jQuery("input:radio[name=wp_resume_section]:checked").val() !== "") {
        return;
      }
      e.preventDefault();
      e.stopPropagation();
      alert(wp_resume.missingTaxMsg);
      jQuery("#ajax-loading").hide();
      setTimeout("jQuery('#publish').removeClass('button-primary-disabled')", 1);
      return false;
    };

    WP_Resume.prototype.toggleMultiple = function() {
      jQuery("#multiple").toggle("fast");
      if (jQuery(this).text() === wp_resume.yes) {
        jQuery(this).text(wp_resume.no);
      } else {
        jQuery(this).text(wp_resume.yes);
      }
      return false;
    };

    WP_Resume.prototype.toggleHood = function() {
      jQuery('.underHood').toggle("fast");
      if (jQuery(this).text() === wp_resume.hideAdv) {
        jQuery(this).text(wp_resume.showAdv);
      } else {
        jQuery(this).text(wp_resume.hideAdv);
      }
      return false;
    };

    WP_Resume.prototype.addContactField = function() {
      jQuery("#contact_info").append(jQuery(".contact_info_blank").html());
      jQuery(".contact_info_row:last").fadeIn();
      return false;
    };

    WP_Resume.prototype.addTaxonomyBoxEvents = function(taxonomy) {
      jQuery("#add_" + taxonomy + "_toggle").live("click", function() {
        var type;
        type = jQuery(this).attr("id").replace("_toggle", "").replace("add_", "");
        return jQuery("#add_" + type + "_div").toggle();
      });
      return jQuery("#add_" + taxonomy + "_button").live("click", function(event) {
        var type;
        type = jQuery(this).attr("id").replace("_button", "").replace("add_", "");
        jQuery("#" + type + "-ajax-loading").show();
        jQuery.post("admin-ajax.php?action=add_" + type, jQuery("#new_" + type + ", #new_" + type + "_location, #_ajax_nonce-add-" + type + ", #post_ID").serialize(), function(data) {
          return jQuery("#" + type + "div .inside").html(data);
        });
        return event.preventDefault();
      });
    };

    WP_Resume.prototype.makeSortable = function() {
      jQuery("#sections, .positions, .organizations").sortable({
        axis: "y",
        containment: "parent",
        opacity: .5,
        update: function() {},
        placeholder: "placeholder",
        forcePlaceholderSize: "true"
      });
      return jQuery("#sections").disableSelection();
    };

    WP_Resume.prototype.submitOptions = function() {
      jQuery(".section").each(function(i, section) {
        return jQuery("#wp_resume_form").append("<input type=\"hidden\" name=\"wp_resume_options[order][" + jQuery(this).attr("id") + "]\" value=\"" + i + "\">");
      });
      return jQuery(".position").each(function(i, position) {
        return jQuery("#wp_resume_form").append("<input type=\"hidden\" name=\"wp_resume_options[position_order][" + jQuery(this).attr("id") + "]\" value=\"" + i + "\">");
      });
    };

    return WP_Resume;

  })();

  jQuery(document).ready(function() {
    return window.resume = new WP_Resume();
  });

}).call(this);
